const text = [
    "I'm baby tumblr hella edison bulb taiyaki everyday carry live-edge. Thundercats edison bulb kitsch activated charcoal. Put a bird on it humblebrag pitchfork pork belly green juice succulents heirloom keytar mlkshk tacos pickled narwhal. Vexillologist gentrify hexagon, blue bottle iPhone aesthetic hella sustainable affogato pitchfork four dollar toast. Green juice photo booth semiotics, bitters cloud bread kickstarter 90's bespoke farm-to-table portland.",
    "Blue bottle gentrify shaman ethical cred roof party waistcoat hexagon selfies green juice. Schlitz knausgaard XOXO, selvage skateboard ethical live-edge copper mug. Stumptown retro tattooed neutra. Ethical four loko +1, lumbersexual meh man bun listicle helvetica stumptown edison bulb raclette pour-over tbh literally. Occupy poutine cold-pressed man braid, narwhal deep v leggings mlkshk keytar quinoa williamsburg irony DIY selvage direct trade. Bespoke whatever blog crucifix forage pour-over thundercats butcher quinoa. Food truck brooklyn glossier shaman four loko keytar edison bulb post-ironic kitsch drinking vinegar schlitz venmo single-origin coffee yuccie.",
    "Blue bottle schlitz XOXO fixie, tacos portland paleo kogi tousled williamsburg. Kombucha literally disrupt poke craft beer banjo viral fanny pack. Sustainable organic pabst typewriter knausgaard kombucha drinking vinegar messenger bag kickstarter hoodie wolf taxidermy intelligentsia photo booth. Small batch af taxidermy street art. Farm-to-table godard skateboard cold-pressed mustache fingerstache authentic blog vice. Ennui roof party kombucha meggings cornhole, pickled chambray hashtag.",
    "Kogi prism af keffiyeh lomo normcore direct trade pop-up letterpress, salvia master cleanse artisan. Helvetica messenger bag scenester taiyaki beard organic iceland next level. Mixtape fingerstache banjo portland butcher DIY truffaut stumptown you probably haven't heard of them biodiesel master cleanse lo-fi kombucha listicle. Disrupt whatever tacos copper mug tofu cardigan poke.",
    "Tofu hell of flexitarian lo-fi, copper mug photo booth chartreuse succulents. Cornhole helvetica tousled flannel twee shabby chic next level small batch. Gochujang tattooed kogi hoodie authentic wolf chartreuse literally tumeric tousled air plant bespoke bushwick small batch ethical. Aesthetic intelligentsia freegan cred edison bulb 90's microdosing enamel pin coloring book tofu meditation. Bushwick vegan celiac forage succulents la croix try-hard authentic seitan edison bulb green juice flexitarian poutine chambray hexagon. Cardigan tbh direct trade intelligentsia man bun disrupt la croix XOXO gochujang affogato slow-carb next level austin.",
    "Dreamcatcher cray literally roof party wolf single-origin coffee scenester lomo yuccie. Migas succulents normcore artisan jianbing tousled gastropub. Cronut cardigan synth meditation 3 wolf moon. Intelligentsia chillwave pinterest mixtape roof party. Tacos palo santo tbh man braid gastropub heirloom truffaut locavore sriracha 8-bit PBR&B.",
    "Deep v sustainable iPhone ramps hoodie pickled. Williamsburg tattooed you probably haven't heard of them, intelligentsia gochujang taxidermy bitters coloring book fixie bushwick letterpress street art authentic. Live-edge try-hard vice, glossier celiac dreamcatcher ramps pitchfork coloring book mumblecore iPhone meditation whatever single-origin coffee bespoke. Unicorn gentrify coloring book hoodie squid, blue bottle thundercats lumbersexual hella chartreuse taxidermy flannel seitan. Post-ironic copper mug pabst organic VHS pug. Glossier taxidermy swag tumeric mlkshk truffaut.",
    "Jean shorts ugh neutra, vinyl vaporware tote bag irony echo park selfies pour-over lumbersexual. Cornhole drinking vinegar glossier, messenger bag pug chicharrones ramps keffiyeh ugh beard. Celiac taxidermy hell of letterpress af microdosing bicycle rights yuccie tumblr direct trade umami listicle. Disrupt leggings +1 bicycle rights echo park blog everyday carry brooklyn listicle direct trade craft beer four dollar toast lomo squid. Coloring book post-ironic unicorn, freegan cray heirloom vexillologist. Austin snackwave direct trade seitan.",
    "Retro literally vexillologist tacos squid mixtape succulents tumeric dreamcatcher sartorial organic. Wayfarers trust fund activated charcoal, DIY kogi celiac unicorn skateboard scenester stumptown copper mug shoreditch chicharrones sriracha gochujang. Yr portland listicle cardigan, taiyaki irony hot chicken franzen. Chillwave hell of tofu pork belly.",
    "Street art chartreuse beard cliche scenester heirloom. Chambray art party mlkshk disrupt, kitsch chia prism pitchfork. Vinyl roof party tilde farm-to-table mustache readymade. Tilde succulents celiac trust fund sriracha copper mug polaroid vegan.",
]

export default text;